# Generated by Django 3.2.8 on 2021-10-24 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0002_booking_movieschedule_theater'),
    ]

    operations = [
        migrations.AddField(
            model_name='movieschedule',
            name='ticket_price',
            field=models.PositiveIntegerField(default=50),
        ),
    ]
